# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegendData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=200)),
                ('line_name', models.CharField(max_length=200)),
            ],
        ),
    ]
