# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contribsourcesbyparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.IntegerField()),
                ('candidate', models.CharField(max_length=200)),
                ('house', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=200)),
                ('year_ran', models.DateField(null=True)),
                ('won', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContributorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('candidate', models.CharField(max_length=200)),
                ('contributor', models.CharField(max_length=200)),
                ('city_state_zip', models.CharField(max_length=200)),
                ('employer', models.CharField(max_length=200)),
                ('interest_category', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('candidate_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CandidateData')),
            ],
        ),
    ]
