# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_candidatedata_contributordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributordata',
            name='candidate_key',
        ),
    ]
