# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_contributordata_candidate_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributordata',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
