# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160221_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributordata',
            name='cumulative',
            field=models.FloatField(default=0),
        ),
    ]
